name: Build, Test, and Deploy Docker Containers

on:
  push:
    branches:
      - main # O la rama que uses para despliegue

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Paso 1: Checkout del c√≥digo
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3: Construir el microservicio de usuarios
      - name: Build Usuarios Service with Maven
        working-directory: ./backend/usuarios-service # Especifica el directorio del microservicio
        run: mvn clean package -DskipTests

      # Paso 4: Construir el API Gateway con Maven
      - name: Build API Gateway with Maven
        working-directory: ./backend/api-gateway # Especifica el directorio del microservicio
        run: mvn clean package -DskipTests

      # Paso 5: Configurar Docker y Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 6: Instalar Docker Compose V2
      - name: Install Docker Compose V2
        run: |
          docker-compose version || curl -SL https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Paso 7: Cacheo de Docker (opcional)
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Paso 8: Imprimir directorio de trabajo
      - name: Print current working directory
        run: pwd

        # Paso (antes del build de Docker)
      - name: List files in backend directory
        run: ls -l ${{ github.workspace }}/backend

        # Paso 9: Docker build
      - name: Build Docker images
        working-directory: ${{ github.workspace }}/backend
        run: |
          docker-compose build
        # Paso 10: Docker clean up
      - name: Clean up Docker containers
        working-directory: ${{ github.workspace }}/backend
        run: |
          docker-compose down
